### ISSUE TITLE
Example app shows 404 

### ISSUE THREAD

**Issue by kristastarr** [carbon-design-system/icons-motion#57]
`npm run deploy` should deploy changes to the gh-pages site.  It worked previously before we set up the redirect but not sure if that has anything to do with it

**Comment by kristastarr** [comment]
@johnbister It’s working now! Did you fix it? 😀

**Comment by johnbister** [comment]
I wish I could take credit!

**Comment by kristastarr** [comment]
Well whatever happened, I’m glad it’s working! 😅
